// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_0xRE2nVEjjQLpmPI5KIqVyBKG_vDMpE',
    appId: '1:210214440308:web:f5b1af0cc75c1cde4ab021',
    messagingSenderId: '210214440308',
    projectId: 'restaurant-app-flutter-27343',
    authDomain: 'restaurant-app-flutter-27343.firebaseapp.com',
    storageBucket: 'restaurant-app-flutter-27343.appspot.com',
    measurementId: 'G-0T43HQ7H3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcTrVR0sqSiutnOYfrWFBJtB0MVOhVnzo',
    appId: '1:210214440308:android:d92f7140aaf12a324ab021',
    messagingSenderId: '210214440308',
    projectId: 'restaurant-app-flutter-27343',
    storageBucket: 'restaurant-app-flutter-27343.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSoixHOV0IsYK_eFIt4g4C0uu0wI313L8',
    appId: '1:210214440308:ios:63b7bc240da1ff154ab021',
    messagingSenderId: '210214440308',
    projectId: 'restaurant-app-flutter-27343',
    storageBucket: 'restaurant-app-flutter-27343.appspot.com',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSoixHOV0IsYK_eFIt4g4C0uu0wI313L8',
    appId: '1:210214440308:ios:dc59f11ec64681904ab021',
    messagingSenderId: '210214440308',
    projectId: 'restaurant-app-flutter-27343',
    storageBucket: 'restaurant-app-flutter-27343.appspot.com',
    iosBundleId: 'com.example.restaurantApp.RunnerTests',
  );
}
